//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2WebApi.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class StudentRegistrationEntities : DbContext
    {
        public StudentRegistrationEntities()
            : base("name=StudentRegistrationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Student> Students { get; set; }
    
        public virtual int spAddStudents(string name, Nullable<System.DateTime> dob, Nullable<decimal> gpa, Nullable<bool> isActive)
        {
            var nameParameter = name != null ?
                new ObjectParameter("name", name) :
                new ObjectParameter("name", typeof(string));
    
            var dobParameter = dob.HasValue ?
                new ObjectParameter("dob", dob) :
                new ObjectParameter("dob", typeof(System.DateTime));
    
            var gpaParameter = gpa.HasValue ?
                new ObjectParameter("gpa", gpa) :
                new ObjectParameter("gpa", typeof(decimal));
    
            var isActiveParameter = isActive.HasValue ?
                new ObjectParameter("isActive", isActive) :
                new ObjectParameter("isActive", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spAddStudents", nameParameter, dobParameter, gpaParameter, isActiveParameter);
        }
    
        public virtual ObjectResult<spGetAllStudents_Result> spGetAllStudents()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetAllStudents_Result>("spGetAllStudents");
        }
    }
}
