//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public System.DateTime DateOfBirth { get; set; }
        public decimal GPA { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
